const Industries=[
    "entertainment",
    "finance",
    "medical",
    "information technology",
    "education",
    "textile",
    "media and news",
    "food processing",
    "hospitality",
    "construction and engineering",
    "law",
    "paper",
    "real estate",
    "automobile",
    "aviation",
    "pharmaceutical",
    "fertilizers",
    "advertising",
    "metallurgy",
    "energy",
    "telecommunications",
    "retail",
    "manufacturing",
    "agriculture",
    "chemicals",
    "transportation and logistics",
    "consumer goods",
    "healthcare"
]

export {Industries}