const serverResponses={
    VerificationFailed:"Token Verification Failed",
    TokenMissing:"Access Token Missing",
    InvalidTokens:"Invalid Tokens",
    Timeout:"Request Timeout"
}

const endPoints=[
    {
        id:"login",
        category:"auth",
        tail:"login",
        type:"POST",
    },
    {
        id:"register",
        category:"auth",
        tail:"student-register",
        type:"POST",
    },
    {
        id:"verify-user",
        category:"auth",
        tail:"verify-user",
        type:"POST",
    },
    {
        id:"block-user",
        category:"student",
        tail:"block",
        type:"POST",
    },
    {
        id:"unblock-user",
        category:"student",
        tail:"unblock",
        type:"POST",
    },
    {
        id:"delete-account",
        category:"student",
        tail:"delete-account",
        type:"GET",
    },
    {
        id:"verify-otp",
        category:"student",
        tail:"verify-otp",
        type:"POST",
    },
    {
        id:"add-phone/email",
        category:"student",
        tail:"phone-email",
        type:"POST",
    },
    {
        id:"reset-password",
        category:"auth",
        tail:"verify-otp",
        type:"POST",
    },
    {
        id:"profile",
        category:"student",
        tail:"profile",
        type:"GET",
    },
    {
        id:"regex",
        category:"public",
        tail:"university",
        type:"GET",
    },
    {
        id:"edit-phone",
        category:"student",
        tail:"phone",
        type:"GET",
    },
    {
        id:"post-review",
        category:"student",
        tail:"post-review",
        type:"GET",
    },
    {
        ENUM:"edit-review",
        TYPE:"student",
        
    },
    {
        id:"dashboard",
        category:"student",
        tail:"dashboard",
        type:"GET",
    },
    {
        ENUM:"check-availability",
        TYPE:"student",
        
    },
    {
        id:"otp-request",
        category:"student",
        tail:"send-sms-otp",
        type:"GET",
    },
    {
        id:"otp-verify",
        category:"student",
        tail:"verify-sms-otp",
        type:"GET",
    },
    {
        id:"email-verification",
        category:"student",
        tail:"verify-email",
        type:"GET",
    },
    {
        id:"forgot-password-getcode",
        category:"auth",
        tail:"forgot-password",
        type:"POST",
    },
    {
        id:"forgot-password-verifycode",
        category:"auth",
        tail:"verify-otp",
        type:"POST",
    },
    {
        id:"checkout",
        category:"student",
        tail:"checkout",
        type:"POST",
    },
    {
        id:"cancel-product",
        category:"student",
        tail:"request-cancellation",
        type:"GET",
    },
    {
        id:"payment-verification",
        category:"student",
        tail:"payment-verification",
        type:"POST",
    },
    {
        id:"generate-recommendations",
        category:"student",
        tail:"generate-recommendations",
        type:"PUT",
    },
    {
        id:"phone",
        category:"student",
        tail:"phone",
        type:"PUT",
    },
    {
        id:"vacant-slots",
        category:"student",
        tail:"events",
        type:"GET",
    },
    {
        id:"book-slot",
        category:"student",
        tail:"book-slot",
        type:"POST",
        
    },
    {
        id:"modify-slot",
        category:"student",
        tail:"modify-slot",
        type:"POST"
        
    },
    {
        id:"request-counsellor",
        category:"student",
        tail:"request-counsellor",
        type:"POST"
        
    },
    {
        id:"upload-profile",
        category:"student",
        tail:"upload-profile",
        type:"POST",
        
    },
    {
        id:"delete-uploaded-profile",
        category:"student",
        tail:"delete-uploaded-profile",
        type:"POST",
    },
    {
        id:"upload-doc-application",
        category:"student",
        tail:"upload-application",
        type:"POST",
        
    },
    {
        id:"delete-doc-application",
        category:"student",
        tail:"delete-uploaded-application",
        type:"POST",
    },
    {
        id:"cart",
        category:"student",
        tail:"cart",
        type:"POST",
    },
    {
        id:"wishlist",
        category:"student",
        tail:"wish-list",
        type:"POST",
    },
    {
        id:"universities",
        category:"public",
        tail:"listings/universities",
        type:"POST",
    },
    {
        id:"universities-new",
        category:"public",
        tail:"newlistings/universities",
        type:"POST",
    },
    {
        id:"programs",
        category:"public",
        tail:"listings/courses",
        type:"POST",
        
    },
    {
        id:"programs-new",
        category:"public",
        tail:"newlistings/courses",
        type:"POST",
        
    },
    {
        id:"program",
        category:"public",
        tail:"single_course",
        type:"GET",
    },
    {
        id:"program-new",
        category:"public",
        tail:"newsingle_course",
        type:"GET",
    },
    {
        id:"university",
        category:"public",
        tail:"single_university",
        type:"POST",
    },
    {
        id:"order-info",
        category:"student",
        tail:"order",
        type:"GET",
    },
    {
        id:"payment-summary",
        category:"student",
        tail:"payment-summary",
        type:"POST",
    },
    {
        id:"add-products",
        category:"student",
        tail:"order",
        type:"POST",
    },
    {
        id:"chats",
        category:"communication",
        tail:"chats",
        type:"POST",
    },
    {
        id:"messages",
        category:"communication",
        tail:"message",
        type:"GET",
    },
    {
        id:"message-send",
        category:"communication",
        tail:"message",
        type:"POST",
    },
    {
        id:"users-search",
        category:"communication",
        tail:"",
        type:"GET",
    },
    {
        id:"add-friend",
        category:"communication",
        tail:"chats",
        type:"GET",
    },
    {
        id:"message-seen",
        category:"communication",
        tail:"seen",
        type:"GET",
    },
]

const baseURL="https://campusroot.com/api/v1"//"https://83e3-124-123-44-188.ngrok-free.app/api/v1"

export {baseURL,endPoints,serverResponses}